export default {
  // local secret key
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  WELCOME: 'WELCOME',

  // database secret
  SQL_DB_HOST: 'SQL_DB_HOST',
  SQL_DB_PORT: 'SQL_DB_PORT',
  SQL_DB_USER: 'SQL_DB_USER',
  SQL_DB_PASSWORD: 'SQL_DB_PASSWORD',
  SQL_DB_NAME: 'SQL_DB_NAME',
  SQL_DB_SYNCHRONIZE: 'SQL_DB_SYNCHRONIZE',

  // mail
  MAIL_SERVICE: 'MAIL_SERVICE',
  MAIL_HOST: 'MAIL_HOST',
  MAIL_USER: 'MAIL_USER',
  MAIL_PASSWORD: 'MAIL_PASSWORD',
  MAIL_FROM: 'MAIL_FROM',

  WEB_SITE_URL: 'WEB_SITE_URL',

  // auth
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
}
